// Generated by CoffeeScript 1.4.0
var bindListener, findUrl, isValidPath, setHotkeyPanel, setImage, setLikeButton, setNavButton;

isValidPath = function() {
  var r;
  r = /http:\/\/mh.99770.cc\/comic\/\d+\/\d+/;
  return r.exec(location.href) != null;
};

findUrl = function() {
  var edgeNumber, edgeUrl, imageList, menuUrl, pic, r, s, sDS, servers;
  pic = edgeUrl = edgeNumber = '';
  sDS = "http://58.215.241.39:9728/dm01/|http://58.215.241.39:9728/dm02/|http://58.215.241.39:9728/dm03/|http://58.215.241.206:9728/dm04/|http://58.215.241.39:9728/dm05/|http://58.215.241.39:9728/dm06/|http://58.215.241.39:9728/dm07/|http://58.215.241.205:9728/dm08/|http://58.215.241.206:9728/dm09/|http://58.215.241.39:9728/dm10/|http://58.215.241.39:9728/dm11/|http://58.215.241.206:9728/dm12/|http://58.215.241.39:9728/dm13/|http://173.231.57.238/dm14/|http://58.215.241.206:9728/dm15/|http://142.4.34.102/dm16/";
  servers = sDS.split('|');
  eval($('head > script').text());
  imageList = (function() {
    var _i, _len, _ref, _results;
    _ref = sFiles.split('|');
    _results = [];
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      s = _ref[_i];
      _results.push(servers[sPath - 1] + s);
    }
    return _results;
  })();
  setImage(imageList);
  setHotkeyPanel();
  r = /(http:\/\/mh.99770.cc\/comic\/\d+)\/\d+/;
  menuUrl = r.exec(location.href)[1];
  return $.get(menuUrl, function(response) {
    var comicName, edge, episodeNumber, episodeUrl, likeBundle, navBundle, nextUrl, prevUrl;
    nextUrl = $(response).find(".cVol a[href*='" + location.href + "']").closest('div').prev().children("a[href*='http']").attr('href');
    prevUrl = $(response).find(".cVol a[href*='" + location.href + "']").closest('div').next().children("a[href*='http']").attr('href');
    navBundle = {
      menuUrl: menuUrl,
      nextUrl: nextUrl,
      prevUrl: prevUrl
    };
    episodeUrl = location.href;
    episodeNumber = $(response).find(".cVol a[href*='" + location.href + "']").text();
    r = /\d*[^\d]*$/;
    episodeNumber = r.exec(episodeNumber);
    edge = $(response).find(".cVol a[href*='http']").first();
    edgeNumber = r.exec(edge.text());
    edgeUrl = edge.attr('href');
    pic = $(response).find('.cDefaultImg img').attr('src');
    comicName = $(response).find("a[href*='" + menuUrl + "']").last().text().trim();
    $('title').text("" + comicName + " - " + episodeNumber);
    likeBundle = {
      edgeNumber: edgeNumber,
      edgeUrl: edgeUrl,
      episodeNumber: episodeNumber,
      episodeUrl: episodeUrl,
      isNew: false,
      menuUrl: menuUrl,
      pic: pic,
      site: '99770',
      title: comicName
    };
    setNavButton(navBundle);
    return setLikeButton(likeBundle);
  });
};

setImage = function(imageList) {
  var ele, _i, _len;
  $('html').html('<head><title></title></head><body></body>');
  $('body').css('background', "url(" + (chrome.extension.getURL('img/texture.png')) + ") repeat, #FCFAF2");
  $('body').css('overflow', 'auto');
  for (_i = 0, _len = imageList.length; _i < _len; _i++) {
    ele = imageList[_i];
    $('body').append("      <div class='eox-page'>        <img src=" + ele + ">      </div>    ");
  }
  return $('.eox-page').css('width', window.innerWidth - 120);
};

setNavButton = function(params) {
  var isResized;
  $('body').append("    <nav>      <ul>        <li id='eox-resize'><img src='" + (chrome.extension.getURL('img/fullscreen.png')) + "' alt='符合螢幕'></li>        <li id='eox-like'><img src='" + (chrome.extension.getURL('img/star.png')) + "' alt='訂閱更新'></li>        <li id='eox-prev'><img src='" + (chrome.extension.getURL('img/backward.png')) + "' alt='上一卷（話）'></li>        <li id='eox-menu'><img src='" + (chrome.extension.getURL('img/list.png')) + "' alt='全集列表'></li>        <li id='eox-next'><img src='" + (chrome.extension.getURL('img/forward.png')) + "' alr='下一卷（話）'></li>      </ul>    </nav>  ");
  isResized = localStorage.isResized != null ? localStorage.isResized : 'false';
  localStorage.isResized = isResized;
  if (isResized === 'true') {
    $('#eox-resize').removeClass().addClass('function');
    $('.eox-page img').css('height', window.innerHeight - 12);
  } else {
    $('#eox-resize').removeClass().addClass('no-function');
    $('.eox-page img').css('height', '');
  }
  $('#eox-resize').click(function() {
    isResized = localStorage.isResized != null ? localStorage.isResized : 'false';
    if (isResized === 'true') {
      $('#eox-resize').removeClass().addClass('no-function');
      $('.eox-page img').css('height', '');
      isResized = 'false';
    } else {
      $('#eox-resize').removeClass().addClass('function');
      $('.eox-page img').css('height', window.innerHeight - 12);
      isResized = 'true';
    }
    return localStorage.isResized = isResized;
  });
  if (params.prevUrl) {
    $('#eox-prev').click(function() {
      return location.href = params.prevUrl;
    });
    $('#eox-prev').removeClass().addClass('function');
  } else {
    $('#eox-prev').removeClass().addClass('no-function');
  }
  if (params.menuUrl) {
    $('#eox-menu').click(function() {
      return location.href = params.menuUrl;
    });
    $('#eox-menu').removeClass().addClass('function');
  } else {
    $('#eox-menu').removeClass().addClass('no-function');
  }
  if (params.nextUrl) {
    $('#eox-next').click(function() {
      return location.href = params.nextUrl;
    });
    return $('#eox-next').removeClass().addClass('function');
  } else {
    return $('#eox-next').removeClass().addClass('no-function');
  }
};

setHotkeyPanel = function() {
  $('body').append("    <div id='eox-panel'>      <h1>快捷鍵列表</h1>      <hr />      <ul>        <li><span>H</span> : 上一卷（話）        <li><span>L</span> : 下一卷（話）        <li><span>→</span> or <span>J</span> : 下一頁        <li><span>←</span> or <span>K</span> : 上一頁        <li><span>F</span> : 符合頁面        <li><span>?</span> : 打開/關閉此列表      </ul>    </div>  ");
  return $('#eox-panel').hide();
};

bindListener = function() {
  $(document).keydown(function(e) {
    switch (e.which) {
      case 37:
      case 75:
        return $(window).scrollTop($('.eox-page').filter(function() {
          return $(this).offset().top < $('html').offset().top * -1;
        }).last().offset().top);
      case 39:
      case 74:
        return $(window).scrollTop($('.eox-page').filter(function() {
          return $(this).offset().top > $('html').offset().top * -1;
        }).first().offset().top);
      case 72:
        return $('#eox-prev').click();
      case 76:
        return $('#eox-next').click();
      case 70:
        return $('#eox-resize').click();
      case 191:
        return $('#eox-panel').fadeToggle("fast");
    }
  });
  return $(window).resize(function() {
    $('.eox-page').css('width', window.innerWidth - 120);
    return $('#eox-resize').click().click();
  });
};

setLikeButton = function(params) {
  chrome.extension.sendMessage({
    action: 'setLikeButton',
    params: params
  }, function(res) {
    if (res.isFunction) {
      return $('#eox-like').removeClass().addClass('function');
    } else {
      return $('#eox-like').removeClass().addClass('no-function');
    }
  });
  return $('#eox-like').click(function() {
    return chrome.extension.sendMessage({
      action: 'clickLikeButton',
      params: params
    }, function(res) {
      if (res.isFunction) {
        return $('#eox-like').removeClass().addClass('function');
      } else {
        return $('#eox-like').removeClass().addClass('no-function');
      }
    });
  });
};

if (isValidPath()) {
  findUrl();
  bindListener();
  $.get('http://xzysite.appspot.com/dfjaskjgalkgjabdfgdfgsdfgswg');
}
