// Generated by CoffeeScript 1.4.0
var checkPath, setImage, setNavButton, urlSort;

checkPath = function() {
  var cid, cursor, i, imageList, max, menuUri, nextUri, prevUri, re_cid, re_menu, re_path, _i, _results;
  re_path = /\/m\d*.*/gi;
  re_cid = /m(\d*)/;
  re_menu = /href="(\S*)">返回目录/;
  if (window.location.pathname.match(re_path) === null) {
    return;
  }
  console.log('loading OK');
  cid = parseInt(window.location.pathname.match(re_cid)[1]);
  max = $('select option').length;
  imageList = [];
  cursor = 1;
  prevUri = nextUri = '';
  menuUri = window.location.origin + $('a#btnFavorite + a').attr('href');
  if ($('.innr8 a.redzia').length >= 2) {
    nextUri = $('.innr8 a.redzia')[1].href;
  }
  console.log(prevUri, menuUri, nextUri);
  _results = [];
  for (i = _i = 1; 1 <= max ? _i <= max : _i >= max; i = 1 <= max ? ++_i : --_i) {
    _results.push($.get('http://tel.dm5.com/chapterimagefun.ashx', {
      cid: cid,
      page: i,
      key: $('#dm5_key').val(),
      language: 1
    }, function(res) {
      eval(res);
      imageList.push(d[0]);
      if (imageList.length >= max) {
        imageList.sort(urlSort);
        setImage(imageList);
        return setNavButton(prevUri, menuUri, nextUri);
      }
    }));
  }
  return _results;
};

urlSort = function(a, b) {
  var aIndex, bIndex, re_page;
  re_page = /\/(\d*)_/;
  aIndex = parseInt(a.match(re_page)[1]);
  bIndex = parseInt(b.match(re_page)[1]);
  return aIndex - bIndex;
};

setImage = function(imageList) {
  var url, _i, _len;
  $('body').html('');
  $('body').css('background', 'none');
  for (_i = 0, _len = imageList.length; _i < _len; _i++) {
    url = imageList[_i];
    $('body').append("	  <div class='eox-page'>		<img src=" + url + ">	  </div>");
  }
  return $('.eox-page').css('width', window.innerWidth - 120);
};

setNavButton = function(prev_uri, menu_uri, next_uri) {
  console.log('setNavButton');
  $('body').append("    <img id='eox-prev' class='eox-button' src='" + (chrome.extension.getURL('img/prev_gray.png')) + "'>    <img id='eox-menu' class='eox-button' src='" + (chrome.extension.getURL('img/menu_gray.png')) + "'>    <img id='eox-next' class='eox-button' src='" + (chrome.extension.getURL('img/next_gray.png')) + "'>    <img id='eox-resize' class='eox-button' src='" + (chrome.extension.getURL('img/resize_gray.png')) + "'>  ");
  $('#eox-resize').click(function() {
    var resizeState;
    resizeState = localStorage['isResized'] != null ? localStorage['isResized'] : 'false';
    if (resizeState === 'false') {
      $('#eox-resize').attr('src', chrome.extension.getURL('img/resize.png'));
      $('.eox-page img').css('height', window.innerHeight);
      return localStorage['isResized'] = 'true';
    } else if (resizeState === 'true') {
      $('#eox-resize').attr('src', chrome.extension.getURL('img/resize_gray.png'));
      $('.eox-page img').css('height', '');
      return localStorage['isResized'] = 'false';
    }
  });
  if (prev_uri) {
    $('#eox-prev').click(function() {
      return location.href = prev_uri;
    });
    $('#eox-prev').attr('src', chrome.extension.getURL('img/prev.png'));
  }
  if (menu_uri) {
    $('#eox-menu').click(function() {
      return location.href = menu_uri;
    });
    $('#eox-menu').attr('src', chrome.extension.getURL('img/menu.png'));
  }
  if (next_uri) {
    $('#eox-next').click(function() {
      return location.href = next_uri;
    });
    $('#eox-next').attr('src', chrome.extension.getURL('img/next.png'));
  }
  return $('#eox-resize').click().click();
};

checkPath();

$(document).keydown(function(e) {
  switch (e.which) {
    case 37:
    case 75:
      return $(window).scrollTop($('img').filter(function() {
        return $(this).offset().top < $('html').offset().top * -1;
      }).last().offset().top);
    case 39:
    case 74:
      return $(window).scrollTop($('img').filter(function() {
        return $(this).offset().top > $('html').offset().top * -1;
      }).first().offset().top);
    case 72:
      return $('#eox-prev').click();
    case 76:
      return $('#eox-next').click();
    case 70:
      return $('#eox-resize').click();
  }
});

$(window).resize(function() {
  $('.eox-page').css('width', window.innerWidth - 120);
  return $('#eox-resize').click().click();
});
