// Generated by CoffeeScript 1.4.0
var checkPath, findUrl, menuUri, nextUri, prevUri, setImage, setNavButton,
  __indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

prevUri = nextUri = menuUri = '';

checkPath = function() {
  var cid, i, imageList, max, re_cid, re_path, _i, _results;
  re_path = /\/m\d*.*/gi;
  re_cid = /m(\d*)/;
  if (window.location.pathname.match(re_path) === null) {
    return;
  }
  console.log('loading OK');
  cid = parseInt(window.location.pathname.match(re_cid)[1]);
  max = $('select option').length;
  menuUri = window.location.origin + $('a#btnFavorite + a').attr('href');
  if ($('.innr8 a.redzia').length >= 2) {
    nextUri = $('.innr8 a.redzia')[1].href;
  }
  console.log(prevUri, menuUri, nextUri);
  imageList = (function() {
    var _i, _results;
    _results = [];
    for (i = _i = 0; 0 <= max ? _i <= max : _i >= max; i = 0 <= max ? ++_i : --_i) {
      _results.push(' ');
    }
    return _results;
  })();
  imageList[0] = 'head';
  _results = [];
  for (i = _i = 1; 1 <= max ? _i <= max : _i >= max; i = 1 <= max ? ++_i : --_i) {
    _results.push(findUrl(i, cid, imageList));
  }
  return _results;
};

findUrl = function(i, cid, imageList) {
  return $.get('http://tel.dm5.com/chapterimagefun.ashx', {
    cid: cid,
    page: i,
    key: $('#dm5_key').val(),
    language: 1
  }, function(res) {
    var a, _i, _len, _results;
    eval(res);
    imageList[i] = d[0];
    if (__indexOf.call(imageList, ' ') < 0) {
      setImage(imageList);
      setNavButton(prevUri, menuUri, nextUri);
      _results = [];
      for (_i = 0, _len = imageList.length; _i < _len; _i++) {
        a = imageList[_i];
        _results.push(console.log(a));
      }
      return _results;
    }
  });
};

setImage = function(imageList) {
  var ele, _i, _len;
  $('body').html('');
  $('body').css('background', 'none');
  imageList.shift();
  for (_i = 0, _len = imageList.length; _i < _len; _i++) {
    ele = imageList[_i];
    $('body').append("	  <div class='eox-page'>		<img src=" + ele + ">	  </div>");
  }
  return $('.eox-page').css('width', window.innerWidth - 120);
};

setNavButton = function(prev_uri, menu_uri, next_uri) {
  console.log('setNavButton');
  $('body').append("    <img id='eox-prev' class='eox-button' src='" + (chrome.extension.getURL('img/prev_gray.png')) + "'>    <img id='eox-menu' class='eox-button' src='" + (chrome.extension.getURL('img/menu_gray.png')) + "'>    <img id='eox-next' class='eox-button' src='" + (chrome.extension.getURL('img/next_gray.png')) + "'>    <img id='eox-resize' class='eox-button' src='" + (chrome.extension.getURL('img/resize_gray.png')) + "'>  ");
  $('#eox-resize').click(function() {
    var resizeState;
    resizeState = localStorage['isResized'] != null ? localStorage['isResized'] : 'false';
    if (resizeState === 'false') {
      $('#eox-resize').attr('src', chrome.extension.getURL('img/resize.png'));
      $('.eox-page img').css('height', window.innerHeight);
      return localStorage['isResized'] = 'true';
    } else if (resizeState === 'true') {
      $('#eox-resize').attr('src', chrome.extension.getURL('img/resize_gray.png'));
      $('.eox-page img').css('height', '');
      return localStorage['isResized'] = 'false';
    }
  });
  if (prev_uri) {
    $('#eox-prev').click(function() {
      return location.href = prev_uri;
    });
    $('#eox-prev').attr('src', chrome.extension.getURL('img/prev.png'));
  }
  if (menu_uri) {
    $('#eox-menu').click(function() {
      return location.href = menu_uri;
    });
    $('#eox-menu').attr('src', chrome.extension.getURL('img/menu.png'));
  }
  if (next_uri) {
    $('#eox-next').click(function() {
      return location.href = next_uri;
    });
    $('#eox-next').attr('src', chrome.extension.getURL('img/next.png'));
  }
  return $('#eox-resize').click().click();
};

checkPath();

$(document).keydown(function(e) {
  switch (e.which) {
    case 37:
    case 75:
      return $(window).scrollTop($('img').filter(function() {
        return $(this).offset().top < $('html').offset().top * -1;
      }).last().offset().top);
    case 39:
    case 74:
      return $(window).scrollTop($('img').filter(function() {
        return $(this).offset().top > $('html').offset().top * -1;
      }).first().offset().top);
    case 72:
      return $('#eox-prev').click();
    case 76:
      return $('#eox-next').click();
    case 70:
      return $('#eox-resize').click();
  }
});

$(window).resize(function() {
  $('.eox-page').css('width', window.innerWidth - 120);
  return $('#eox-resize').click().click();
});
