// Generated by CoffeeScript 1.4.0
var bindListener, findUrl, setHotkeyPanel, setImage, setLikeButton, setNavButton;

findUrl = function() {
  var jsName, targetScriptUrl;
  jsName = location.pathname.match(/\/([^\/]*)\/$/)[1];
  targetScriptUrl = location.origin + $("script[src*='" + jsName + "']").attr('src');
  return $.get(targetScriptUrl, function(response) {
    var menuUrl, navBundle, nextUrl, prevUrl;
    eval(response);
    menuUrl = $("[href*='HTML']").attr('href') || '';
    nextUrl = nextVolume.indexOf('http') === 0 ? nextVolume : '';
    prevUrl = preVolume.indexOf('http') === 0 ? preVolume : '';
    navBundle = {
      menuUrl: menuUrl,
      nextUrl: nextUrl,
      prevUrl: prevUrl
    };
    setImage(picAy);
    setNavButton(navBundle);
    setHotkeyPanel();
    return $.get(menuUrl, function(response) {
      var edge, edgeNumber, edgeUrl, episodeNumber, episodeUrl, likeBundle, pic;
      episodeUrl = location.href;
      episodeNumber = $(response).find("a[href='" + episodeUrl + "']").text();
      edge = $(response).find('.serialise_list:last li:first-child');
      edgeNumber = edge.text();
      edgeUrl = edge.find('a').attr('href');
      pic = $(response).find('.comic_cover img').attr('src');
      likeBundle = {
        edgeNumber: edgeNumber,
        edgeUrl: edgeUrl,
        episodeNumber: episodeNumber,
        episodeUrl: episodeUrl,
        isNew: false,
        menuUrl: menuUrl,
        pic: pic,
        site: 'sfacg',
        title: comicName
      };
      return setLikeButton(likeBundle);
    });
  });
};

setImage = function(imageList) {
  var ele, _i, _len;
  $('html').html('<body></body>');
  $('body').css('background', "url(" + (chrome.extension.getURL('img/texture.png')) + ") repeat, #FCFAF2");
  $('body').css('overflow', 'auto');
  for (_i = 0, _len = imageList.length; _i < _len; _i++) {
    ele = imageList[_i];
    $('body').append("      <div class='eox-page'>        <img src=" + ele + ">      </div>    ");
  }
  return $('.eox-page').css('width', window.innerWidth - 120);
};

setNavButton = function(params) {
  var isResized;
  $('body').append("    <nav>      <ul>        <li id='eox-resize'><img src='" + (chrome.extension.getURL('img/fullscreen.png')) + "' alt='符合螢幕'></li>        <li id='eox-like'><img src='" + (chrome.extension.getURL('img/star.png')) + "' alt='訂閱更新'></li>        <li id='eox-prev'><img src='" + (chrome.extension.getURL('img/backward.png')) + "' alt='上一卷（話）'></li>        <li id='eox-menu'><img src='" + (chrome.extension.getURL('img/list.png')) + "' alt='全集列表'></li>        <li id='eox-next'><img src='" + (chrome.extension.getURL('img/forward.png')) + "' alr='下一卷（話）'></li>      </ul>    </nav>  ");
  isResized = localStorage.isResized != null ? localStorage.isResized : 'false';
  localStorage.isResized = isResized;
  if (isResized === 'true') {
    $('#eox-resize').removeClass().addClass('function');
    $('.eox-page img').css('height', window.innerHeight - 12);
  } else {
    $('#eox-resize').removeClass().addClass('no-function');
    $('.eox-page img').css('height', '');
  }
  $('#eox-resize').click(function() {
    isResized = localStorage.isResized != null ? localStorage.isResized : 'false';
    if (isResized === 'true') {
      $('#eox-resize').removeClass().addClass('no-function');
      $('.eox-page img').css('height', '');
      isResized = 'false';
    } else {
      $('#eox-resize').removeClass().addClass('function');
      $('.eox-page img').css('height', window.innerHeight - 12);
      isResized = 'true';
    }
    return localStorage.isResized = isResized;
  });
  if (params.prevUrl) {
    $('#eox-prev').click(function() {
      return location.href = params.prevUrl;
    });
    $('#eox-prev').removeClass().addClass('function');
  } else {
    $('#eox-prev').removeClass().addClass('no-function');
  }
  if (params.menuUrl) {
    $('#eox-menu').click(function() {
      return location.href = params.menuUrl;
    });
    $('#eox-menu').removeClass().addClass('function');
  } else {
    $('#eox-menu').removeClass().addClass('no-function');
  }
  if (params.nextUrl) {
    $('#eox-next').click(function() {
      return location.href = params.nextUrl;
    });
    return $('#eox-next').removeClass().addClass('function');
  } else {
    return $('#eox-next').removeClass().addClass('no-function');
  }
};

setHotkeyPanel = function() {
  $('body').append("    <div id='eox-panel'>      <h1>快捷鍵列表</h1>      <hr />      <ul>        <li><span>H</span> : 上一卷（話）        <li><span>L</span> : 下一卷（話）        <li><span>→</span> or <span>J</span> : 下一頁        <li><span>←</span> or <span>K</span> : 上一頁        <li><span>F</span> : 符合頁面        <li><span>?</span> : 打開/關閉此列表      </ul>    </div>  ");
  return $('#eox-panel').hide();
};

bindListener = function() {
  $(document).keydown(function(e) {
    switch (e.which) {
      case 37:
      case 75:
        return $(window).scrollTop($('.eox-page').filter(function() {
          return $(this).offset().top < $('html').offset().top * -1;
        }).last().offset().top);
      case 39:
      case 74:
        return $(window).scrollTop($('.eox-page').filter(function() {
          return $(this).offset().top > $('html').offset().top * -1;
        }).first().offset().top);
      case 72:
        return $('#eox-prev').click();
      case 76:
        return $('#eox-next').click();
      case 70:
        return $('#eox-resize').click();
      case 191:
        return $('#eox-panel').fadeToggle("fast");
    }
  });
  return $(window).resize(function() {
    $('.eox-page').css('width', window.innerWidth - 120);
    return $('#eox-resize').click().click();
  });
};

setLikeButton = function(params) {
  chrome.extension.sendMessage({
    action: 'setLikeButton',
    params: params
  }, function(res) {
    if (res.isFunction) {
      return $('#eox-like').removeClass().addClass('function');
    } else {
      return $('#eox-like').removeClass().addClass('no-function');
    }
  });
  return $('#eox-like').click(function() {
    return chrome.extension.sendMessage({
      action: 'clickLikeButton',
      params: params
    }, function(res) {
      if (res.isFunction) {
        return $('#eox-like').removeClass().addClass('function');
      } else {
        return $('#eox-like').removeClass().addClass('no-function');
      }
    });
  });
};

$(function() {
  findUrl();
  return bindListener();
});
