// Generated by CoffeeScript 1.4.0
var checkList, checkUpdate8comic, checkUpdate99770, checkUpdateDm5, checkUpdateSfacg, cview, onAlarm, onInit, onLikeButton, scheduleRequest, startRequest, sync;

onLikeButton = function(request, sender, sendResponse) {
  var badgeText, e, ele, i, j, newCount, userList, _i, _j, _len, _len1;
  console.log('onMessage', request);
  userList = JSON.parse(localStorage.userList);
  switch (request.action) {
    case 'setLikeButton':
      console.log('setLikeButton');
      for (_i = 0, _len = userList.length; _i < _len; _i++) {
        ele = userList[_i];
        if (ele.menuUrl === request.params.menuUrl) {
          ele.episodeUrl = request.params.episodeUrl;
          ele.episodeNumber = request.params.episodeNumber;
          ele.isNew = false;
          newCount = ((function() {
            var _j, _len1, _results;
            _results = [];
            for (_j = 0, _len1 = userList.length; _j < _len1; _j++) {
              ele = userList[_j];
              if (ele.isNew) {
                _results.push(ele);
              }
            }
            return _results;
          })()).length;
          badgeText = newCount !== 0 ? '' + newCount : '';
          chrome.browserAction.setBadgeText({
            text: badgeText
          });
          localStorage.userList = JSON.stringify(userList);
          sync();
          sendResponse({
            isFunction: true
          });
          return;
        }
      }
      return sendResponse({
        isFunction: false
      });
    case 'clickLikeButton':
      console.log('clickLikeButton');
      for (i = _j = 0, _len1 = userList.length; _j < _len1; i = ++_j) {
        ele = userList[i];
        if (ele.menuUrl === request.params.menuUrl) {
          userList = (function() {
            var _k, _len2, _results;
            _results = [];
            for (j = _k = 0, _len2 = userList.length; _k < _len2; j = ++_k) {
              e = userList[j];
              if (i !== j) {
                _results.push(e);
              }
            }
            return _results;
          })();
          localStorage.userList = JSON.stringify(userList);
          sync();
          sendResponse({
            isFunction: false
          });
          return;
        }
      }
      userList.push(request.params);
      localStorage.userList = JSON.stringify(userList);
      sync();
      return sendResponse({
        isFunction: true
      });
  }
};

chrome.extension.onMessage.addListener(onLikeButton);

onInit = function() {
  console.log('onInit');
  localStorage.timestamp = '0';
  localStorage.userList = localStorage.userList || '[]';
  sync();
  chrome.tabs.create({
    url: chrome.extension.getURL('options.html')
  });
  return startRequest({
    scheduleRequest: true
  });
};

startRequest = function(params) {
  var targetComic, userList, _i, _len, _results;
  console.log('startRequest');
  if ((params != null) && params.scheduleRequest) {
    scheduleRequest();
  }
  userList = JSON.parse(localStorage.userList || []);
  _results = [];
  for (_i = 0, _len = userList.length; _i < _len; _i++) {
    targetComic = userList[_i];
    switch (targetComic.site) {
      case 'dm5':
        _results.push(checkUpdateDm5(targetComic));
        break;
      case '8comic':
        _results.push(checkUpdate8comic(targetComic));
        break;
      case 'sfacg':
        _results.push(checkUpdateSfacg(targetComic));
        break;
      case '99770':
        _results.push(checkUpdate99770(targetComic));
        break;
      default:
        _results.push(console.log(targetComic));
    }
  }
  return _results;
};

checkUpdate99770 = function(targetComic) {
  return $.get(targetComic.menuUrl, function(response) {
    var edge, edgeNumber, edgeUrl, newBundle, r;
    edge = $(response).find(".cVol a[href*='http']").first();
    r = /\d*[^\d]*$/;
    edgeNumber = r.exec(edge.text())[0];
    edgeUrl = edge.attr('href');
    newBundle = {
      edgeNumber: edgeNumber,
      edgeUrl: edgeUrl,
      menuUrl: targetComic.menuUrl,
      site: targetComic.site,
      title: targetComic.title
    };
    return checkList(newBundle);
  });
};

checkUpdateSfacg = function(targetComic) {
  return $.get(targetComic.menuUrl, function(response) {
    var edge, edgeNumber, edgeUrl, newBundle, title;
    edge = $(response).find('.serialise_list').last().find('li').first();
    edgeNumber = edge.text();
    edgeUrl = edge.find('a').attr('href');
    title = $(response).find('b.F14PX').text();
    newBundle = {
      edgeNumber: edgeNumber,
      edgeUrl: edgeUrl,
      menuUrl: targetComic.menuUrl,
      site: targetComic.site,
      title: targetComic.title
    };
    return checkList(newBundle);
  });
};

checkUpdate8comic = function(targetComic) {
  return $.get(targetComic.menuUrl, function(response) {
    var callback, cell, edgeNumber, edgeUrl, newBundle, params, re_callback;
    cell = $(response).find('a.Ch, a.Vol').last();
    edgeNumber = cell.text().trim();
    callback = cell.attr('onclick');
    re_callback = /'(.*)',(.*)\)/;
    params = callback.match(re_callback);
    edgeUrl = cview(params[1], params[2]);
    newBundle = {
      edgeNumber: edgeNumber,
      edgeUrl: edgeUrl,
      menuUrl: targetComic.menuUrl,
      site: targetComic.site,
      title: targetComic.title
    };
    return checkList(newBundle);
  });
};

checkUpdateDm5 = function(targetComic) {
  return $.get(targetComic.menuUrl, function(response) {
    var mid, r;
    r = /DM5_COMIC_MID=(\d+)/;
    mid = r.exec(response)[1];
    return $.get("http://tel.dm5.com/template-" + mid + "/?language=1", function(response) {
      var edgeNumber, edgeUrl, newBundle;
      edgeNumber = $(response).find('#chapter_1 tr a').first().text().match(/( - )(\S*)/)[2];
      edgeUrl = 'http://tel.dm5.com' + $(response).find('#chapter_1 tr a').first().attr('href');
      newBundle = {
        edgeNumber: edgeNumber,
        edgeUrl: edgeUrl,
        menuUrl: targetComic.menuUrl,
        site: targetComic.site,
        title: targetComic.title
      };
      return checkList(newBundle);
    });
  });
};

scheduleRequest = function() {
  var delay;
  console.log('scheduleRequest');
  delay = 30;
  console.log("Scheduling for: " + delay + " min");
  return chrome.alarms.create('refresh', {
    periodInMinutes: delay
  });
};

checkList = function(params) {
  var badgeText, ele, i, isNew, isSubscriber, newCount, userList, _i, _len;
  userList = JSON.parse(localStorage.userList || []);
  for (i = _i = 0, _len = userList.length; _i < _len; i = ++_i) {
    ele = userList[i];
    isSubscriber = ele.menuUrl === params.menuUrl;
    isNew = ele.edgeUrl !== params.edgeUrl;
    if (isSubscriber && isNew) {
      console.log('just updated');
      ele.isNew = isNew;
      ele.edgeUrl = params.edgeUrl;
      ele.edgeNumber = params.edgeNumber;
      localStorage.userList = JSON.stringify(userList);
      sync();
      break;
    } else if (isSubscriber) {
      console.log('already updated');
    }
  }
  newCount = ((function() {
    var _j, _len1, _results;
    _results = [];
    for (_j = 0, _len1 = userList.length; _j < _len1; _j++) {
      ele = userList[_j];
      if (ele.isNew) {
        _results.push(ele);
      }
    }
    return _results;
  })()).length;
  badgeText = newCount !== 0 ? '' + newCount : '';
  return chrome.browserAction.setBadgeText({
    text: badgeText
  });
};

onAlarm = function(alarm) {
  console.log('Got alarm');
  if ((alarm != null) && alarm.name === 'refresh') {
    return startRequest({
      scheduleRequest: true
    });
  }
};

cview = function(url, catid) {
  var baseurl;
  baseurl = '';
  catid = parseInt(catid);
  switch (catid) {
    case 4:
    case 6:
    case 12:
    case 22:
      baseurl = 'http://www.8comic.com/show/cool-';
      break;
    case 1:
    case 17:
    case 19:
    case 21:
      baseurl = 'http://www.8comic.com/show/cool-';
      break;
    case 2:
    case 5:
    case 7:
    case 9:
      baseurl = 'http://www.8comic.com/show/cool-';
      break;
    case 10:
    case 11:
    case 13:
    case 14:
      baseurl = 'http://www.8comic.com/show/best-manga-';
      break;
    case 3:
    case 8:
    case 15:
    case 16:
    case 18:
    case 20:
      baseurl = 'http://www.8comic.com/show/best-manga-';
  }
  url = url.replace('.html', '').replace('-', '.html?ch=');
  return baseurl + url;
};

sync = function() {
  var bundle, t, timestamp;
  if (localStorage.isSync === 'true') {
    t = new Date();
    timestamp = localStorage.timestamp = '' + Math.round(t.getTime() / 1000);
    bundle = {
      account: localStorage.account,
      password: localStorage.password,
      userlist: localStorage.userList,
      timestamp: localStorage.timestamp
    };
    return $.post('http://xzysite.appspot.com/bookmark', bundle, function(response) {
      console.log(response);
      if (response.status === 'overwrite') {
        localStorage.userList = response.userlist;
        return localStorage.timestamp = response.timestamp;
      }
    });
  }
};

chrome.runtime.onInstalled.addListener(onInit);

chrome.alarms.onAlarm.addListener(onAlarm);
