// Generated by CoffeeScript 1.4.0
var bind, loadEpisode, refreshBadge, setPicture, userList;

userList = localStorage.userList != null ? JSON.parse(localStorage.userList) : [];

localStorage.userList = JSON.stringify(userList);

console.log(userList);

refreshBadge = function() {
  var badgeText, ele, newCount, tempHtml, unreadList;
  newCount = ((function() {
    var _i, _len, _results;
    _results = [];
    for (_i = 0, _len = userList.length; _i < _len; _i++) {
      ele = userList[_i];
      if (ele.isNew) {
        _results.push(ele);
      }
    }
    return _results;
  })()).length;
  badgeText = newCount !== 0 ? '' + newCount : '';
  chrome.browserAction.setBadgeText({
    text: badgeText
  });
  unreadList = ((function() {
    var _i, _len, _results;
    _results = [];
    for (_i = 0, _len = userList.length; _i < _len; _i++) {
      ele = userList[_i];
      if (ele.isNew) {
        _results.push(ele);
      }
    }
    return _results;
  })()) || [];
  tempHtml = "    <section id='site' class='clearfix'>      <ul>        <li><div id='eightComicLink'>8Comic.com 無限動漫</div>        <li><div id='dm5Link'>Dm5 动漫屋</div>      </ul>    </section>";
  $('.container').html(tempHtml);
  $('#eightComicLink').click(function() {
    return chrome.tabs.create({
      url: 'http://www.8comic.com/comic/'
    });
  });
  $('#dm5Link').click(function() {
    return chrome.tabs.create({
      url: 'http://tel.dm5.com/'
    });
  });
  return loadEpisode();
};

loadEpisode = function() {
  var ele, i, user8comicList, userDm5List, _i, _j, _len, _len1, _results;
  userDm5List = ((function() {
    var _i, _len, _results;
    _results = [];
    for (_i = 0, _len = userList.length; _i < _len; _i++) {
      ele = userList[_i];
      if (ele.site === 'dm5') {
        _results.push(ele);
      }
    }
    return _results;
  })()) || [];
  user8comicList = ((function() {
    var _i, _len, _results;
    _results = [];
    for (_i = 0, _len = userList.length; _i < _len; _i++) {
      ele = userList[_i];
      if (ele.site === '8comic') {
        _results.push(ele);
      }
    }
    return _results;
  })()) || [];
  if (user8comicList != null) {
    $('.container').append("      <section id='eightComic' class='column'>        <ul></ul>      </section>");
    for (i = _i = 0, _len = user8comicList.length; _i < _len; i = ++_i) {
      ele = user8comicList[i];
      $('#eightComic ul').append("        <li id='eightComic-" + i + "'>          <div class='new'>NEW</div>          <div class='cover'>            <img src='" + ele.pic + "'>          </div>          <div class='info'>            <div class='title'>" + ele.title + "</div>            <div class='episode'>看到 " + ele.episodeNumber + "</div>            <div class='edge'>更新到 " + ele.edgeNumber + "</div>          </div>          <input type='button' value='續看'>        </li>");
      if (!ele.isNew) {
        $("#eightComic-" + i + " .new").css('display', 'none');
      }
    }
  }
  if (userDm5List != null) {
    $('.container').append("      <section id='dm5' class='column'>        <ul></ul>      </section>");
    _results = [];
    for (i = _j = 0, _len1 = userDm5List.length; _j < _len1; i = ++_j) {
      ele = userDm5List[i];
      $('#dm5 ul').append("        <li id='dm5-" + i + "'>          <div class='new'>NEW</div>          <div class='cover'>            <img src='" + ele.pic + "'>          </div>          <div class='info'>            <div class='title'>" + ele.title + "</div>            <div class='episode'>看到 " + ele.episodeNumber + "</div>            <div class='edge'>更新到 " + ele.edgeNumber + "</div>          </div>          <input type='button' value='續看'>        </li>");
      if (!ele.isNew) {
        _results.push($("#dm5-" + i + " .new").css('display', 'none'));
      } else {
        _results.push(void 0);
      }
    }
    return _results;
  }
};

bind = function(target, params) {
  $(target).click(function() {
    return chrome.tabs.create({
      url: params.episodeUrl
    });
  });
  return $(target).find('.dismiss').click(function() {
    var ele, unreadList;
    console.log('params', params);
    unreadList = localStorage.unreadList != null ? JSON.parse(localStorage.unreadList) : [];
    unreadList = (function() {
      var _i, _len, _results;
      _results = [];
      for (_i = 0, _len = unreadList.length; _i < _len; _i++) {
        ele = unreadList[_i];
        if (ele.menuUrl !== params.menuUrl) {
          _results.push(ele);
        }
      }
      return _results;
    })();
    localStorage.unreadList = JSON.stringify(unreadList);
    $(target).remove();
    return refreshBadge();
  });
};

setPicture = function(i, targetURL) {
  var target_id,
    _this = this;
  target_id = "#go" + i;
  $(target_id).attr('src', 'image/arrow.png');
  return $(target_id).click(function() {
    var epi, newEpisodeList, _i, _len;
    chrome.tabs.create({
      url: targetURL
    });
    $(target_id).parent().remove();
    newEpisodeList = [];
    for (_i = 0, _len = episodeList.length; _i < _len; _i++) {
      epi = episodeList[_i];
      if (epi.url !== targetURL) {
        newEpisodeList.push(epi);
      }
    }
    ls.episodeList = JSON.stringify(newEpisodeList);
    return refreshBadge();
  });
};

$(document).ready(function() {
  $('body').css('background', "url(" + (chrome.extension.getURL('img/texture.png')) + ") repeat, #FCFAF2");
  return refreshBadge();
});
